subinclude("//build/defs:terraform")

terraform_module(
    name = "gcp",
    srcs = [
        "cleanup.tf",
        "kms.tf",
        "main.py",
        "main.tf",
        "outputs.tf",
        "requirements.txt",
        "variables.tf",
    ],
    visibility = ["PUBLIC"],
)
