go_binary(
    name = "aws-cross-account",
    srcs = ["main.go"],
    deps = [
        "//internal/logging",
        "//third_party/go:ini_ini",
        "//third_party/go:jessevdk_flags",
        "//third_party/go:aws_aws-sdk",
    ],
    visibility = ["PUBLIC"],
)
