subinclude("//build/defs:sh")

sh_script(
    name = "state_generator",
    main = "state_generator.sh",
    visibility = ["PUBLIC"],
    deps = [
        "//build/util",
        "//third_party/sh:shflags",
    ],
)
