---
name: "Terraform"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_jobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate list of Terraform workspaces as JSON
      run: "./pleasew -p -v2 run //build/github:terraform_workspaces -- plz-out/github/terraform_workspaces.json"
    - id: set-terraform-workspaces
      name: Set Terraform workspaces output
      run: echo "::set-output name=terraform-workspaces::$(<plz-out/github/terraform_workspaces.json)"
    outputs:
      terraform-workspaces: ${{ steps.set-terraform-workspaces.outputs.terraform-workspaces }}
    
  terraform_plan:
    if: github.event_name == 'pull_request'
    name: "Plan"
    needs: generate_jobs
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        terraform-workspace: ${{ fromJson(needs.generate_jobs.outputs.terraform-workspaces) }}
    concurrency: "${{ matrix.terraform-workspace }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'ghapr-vjftw-org-infra@vjp-github-actions.iam.gserviceaccount.com'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::400744676526:role/ghapr-vjftw-org-infra
          aws-region: us-east-1

      - name: "Terraform: Plan"
        run: ./pleasew run -v=2 -p //build/github:terraform_plan -- "${{ matrix.terraform-workspace }}"

  terraform_apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: "Apply"
    needs: generate_jobs
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        terraform-workspace: ${{ fromJson(needs.generate_jobs.outputs.terraform-workspaces) }}
    concurrency: "${{ matrix.terraform-workspace }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'gha-vjftw-org-infra-main@vjp-github-actions.iam.gserviceaccount.com'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::400744676526:role/gha-vjftw-org-infra
          aws-region: us-east-1

      - name: "Terraform: Apply"
        run: ./pleasew run -v=2 -p //build/github:terraform_apply -- "${{ matrix.terraform-workspace }}"
